### PR TITLE
Use nameyeardelim

### PR DESCRIPTION
**Pull request by moewew**
Make use of `(no)nameyeardelim` where appropriate for easier customisation.

Inspired by https://tex.stackexchange.com/q/553151/35864.

### CODE REVIEW

**Comment by moewew** [comment]
I know this isn't strictly necessary for APA compliance, but I think it might be a useful addition given questions like https://tex.stackexchange.com/q/401396/35864 and https://tex.stackexchange.com/q/553151/35864 on TeX.SX. Would you consider merging this PR?

**Comment by plk** [comment]
Yes, I see no reason not to do this - I haven't retrofitted many newer features which probably should be - does this PR still work against the latest version?

**Comment by moewew** [comment]
I expect it should. The pull request says it merges cleanly (I just tried it locally and it appears to work).

**Comment by plk** [comment]
One issue with this from page 5 (reference doc on left):

Screenshot 2021-06-23 at 9 51 pm

**Comment by moewew** [comment]
https://github.com/plk/biblatex-apa/pull/148 should hopefully fix that.

**Pull request merged**
