### PR TITLE
Use date formats properly (#159)

### PR DESCRIPTION
**Pull request by moewew**
Should hopefully fix the missing strings from #159

### CODE REVIEW

**Comment by plk** [comment]
Much better - only one issue now - 10.1:11 (Shore 2014) now has a period after the first DOI link but doesn't in the reference PDF.

**Comment by moewew** [comment]
Argh! I shall have a look at that. But it'll have to be later.

**Comment by plk** [comment]
Apologies, you were right, the error was in the reference document after checking this with the physical manual so it seems that this is all fine now.

**Comment by moewew** [comment]
Phew!

**Pull request merged**
