### PR TITLE
Fix "In" typesetting (#144)

### PR DESCRIPTION
**Pull request by moewew**

### CODE REVIEW

**Comment by plk** [comment]
Just one difference, left is the reference file, right is the test file after changes:

Screenshot 2021-06-19 at 10 50 pm

**Comment by moewew** [comment]
Ah good. Thank you very much for checking.

As explained in https://github.com/plk/biblatex-apa/pull/144 I believe that "Olive, K. A., et al." would be even more consistent with APA style than "Olive, K. A. et al.". So I would leave things as they are and update the reference PDF. Do you want me to try and get rid of the comma?

**Comment by plk** [comment]
I wonder if it's worth asking on the APA blog about this example as personally, I don't like the comma there but that would at least be an answer to follow ...

**Comment by moewew** [comment]
Yeah, maybe, but if I understand correctly, you should never end up in a situation where you have a name in family-given order followed by "et al." in APA style, so they might just say that this should not happen.

**Pull request merged**
